# Generated by Django 3.0.5 on 2020-04-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200424_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test3',
        ),
    ]
